site_name: hagerstrand

site_url: https://jimmy-feng.github.io/hagerstrand

repo_url: https://github.com/jimmy-feng/hagerstrand

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
         - navigation.expand
         - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          execute: False
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# google_analytics:
#     - UA-XXXXXXXXX-X
#     - auto

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Report Issues: https://github.com/jimmy-feng/hagerstrand/issues
    - API Reference:
          - hagerstrand module: hagerstrand.md
          - dataprocess module: dataprocess.md
          - common module: common.md
    - Notebooks:
          - notebooks/Basic_Mapping.ipynb
          - notebooks/Add_Filter_Geo_Map.ipynb
          - notebooks/Add_GoogleMapsJSON_Map.ipynb
          - notebooks/SafeGraph.ipynb
